import type { Content } from "@/content/types";

/**
 * English content. Every figure here is real or absent — never estimate a
 * metric to fill a gap.
 */
export const en: Content = {
  lang: "en",

  sheets: [
    {
      path: "/",
      tab: "Identity",
      seoTitle: "Dimitri MedNov",
      seoDescription:
        "Identity and measured results of Jesus D'mitri Medina Novelo: CRM and automation in production at Diprolam, an ERP for 100+ users in development.",
    },
    {
      path: "/systems",
      tab: "Systems",
      seoTitle: "Systems",
      seoDescription:
        "Private enterprise work: corporate ERP, multi-tenant SaaS, enterprise CRM, AI integrations and OCR archive search, with the sites they run in.",
    },
    {
      path: "/projects",
      tab: "Builds",
      seoTitle: "Public Projects",
      seoDescription:
        "Six public projects with live demos: ShopEdge, Chainlytics, MindTask AI, Weather App, Beat Pulse and El Taquito Gordo Feliz.",
    },
    {
      path: "/about",
      tab: "Resume",
      seoTitle: "Resume",
      seoDescription:
        "Full resume: 4.5+ years across Diprolam, Grupo Megamedia and Universidad Anáhuac Mayab, with responsibilities, stack, education, certifications and courses.",
    },
    {
      path: "/contact",
      tab: "Contact",
      seoTitle: "Contact",
      seoDescription:
        "Contact Jesus D'mitri Medina Novelo — mednov@outlook.es, +52 999 359 0366, Mérida, Yucatán, Mexico.",
    },
  ],

  ui: {
    role: "AI systems engineering",
    availability: "Open to work",
    themeToDark: "Switch to dark mode",
    themeToLight: "Switch to light mode",
    langSwitch: "Ver en español",
    navLabel: "Sections",
    skipDemo: "Live demo",
    source: "Source",
    copy: "Copy",
    copied: "copied",
    copyFailed: "Could not copy",
    copyFailedHint: "Select the text and copy it manually.",
    modelView: "Model view",
    inference: "inference",
    live: "live",
    units: "4 layers · 21 units",
    channelOpen: "channel open",
  },

  hero: {
    eyebrow: "Open to work",
    name: "Jesus D'mitri",
    surname: "Medina Novelo",
    summary:
      "I lead IT and software engineering at Diprolam, an industrial supplier with sites in Monterrey, Guanajuato, Puebla and Tijuana, where the CRM, the inventory system and the purchasing flow I built are already part of how the company works day to day while I put together the ERP that more than 100 people will work in and a multi-tenant SaaS platform beside it, after two years at Grupo Megamedia and its century-old newspaper putting AI where it saved real work: chatbots, automated financial summaries and OCR search across the archive.",
    ctaSystems: "View systems",
    ctaContact: "Open channel",
  },

  idFields: [
    { k: "Name", v: "Dimitri MedNov" },
    { k: "Based in", v: "Mérida, Yucatán, MX" },
    { k: "Coordinates", v: "20.9674 N · 89.5926 W" },
    { k: "Experience", v: "4.5+ years" },
    { k: "GitHub", v: "github/DimitriMedNov", href: "https://github.com/DimitriMedNov" },
    { k: "LinkedIn", v: "linkedin/dimitrimednoov", href: "https://www.linkedin.com/in/dimitrimednoov" },
    { k: "Email", v: "mednov@outlook.es", href: "mailto:mednov@outlook.es" },
    { k: "Phone", v: "+52 999 359 0366", href: "tel:+529993590366" },
  ],

  systems: {
    title: "Systems — private work",
    note: "mostly internal systems · no public repositories",
    stackLabel: "Stack manifest",
    resultLabel: "Recorded result",
    cases: [
      {
        id: "erp",
        logo: "/logos/diprolam.png",
        desig: "DPL-ERP/01",
        org: "Diprolam",
        year: "2026",
        statusLabel: "In development",
        status: "test",
        access: { label: "Internal use", public: false },
        title: "Corporate ERP",
        desc: "One ERP for more than 100 users across the four operating cities, pulling inventory, procurement, warehouse, suppliers and the administrative side into a single system instead of the handful of tools and spreadsheets each city had grown on its own.",
        stack: ["Python", "React 19", "TypeScript", "TanStack", "Supabase", "Docker", "AWS"],
        reads: [
          { v: "+100", l: "users" },
          { v: "4", l: "cities" },
        ],
      },
      {
        id: "saas",
        logo: "/logos/diprolam.png",
        desig: "DPL-SAAS/02",
        org: "Diprolam",
        year: "2026",
        statusLabel: "In development",
        status: "test",
        access: { label: "Internal use", public: false },
        title: "Multi-tenant SaaS platform",
        desc: "Platform that takes the paperwork of the business into software, with authentication, file storage, document generation and role-based access control, built multi-tenant so each part of the company works in its own space without stepping on the others.",
        stack: ["React 19", "TypeScript", "TanStack", "Supabase", "Zod", "Vercel"],
        reads: [],
      },
      {
        id: "crm",
        logo: "/logos/diprolam.png",
        desig: "DPL-CRM/03",
        org: "Diprolam",
        year: "2026",
        statusLabel: "In production",
        status: "pass",
        access: { label: "Internal use", public: false },
        title: "Enterprise CRM",
        desc: "CRM where the sales side of the company lives across its four cities: customers, the pipeline, every open opportunity and the follow-up each one needs, so the commercial team stops keeping that in their own heads and their own files.",
        stack: ["Python", "React", "TypeScript", "Supabase", "PostgreSQL", "Linux", "DigitalOcean"],
        reads: [{ v: "4", l: "cities" }],
      },
      {
        id: "inventory",
        logo: "/logos/diprolam.png",
        desig: "DPL-INV/04",
        org: "Diprolam",
        year: "2026",
        statusLabel: "In production",
        status: "pass",
        access: { label: "Internal use", public: false },
        title: "Inventory management",
        desc: "Software that follows every tool and every item across the four sites, so each movement carries a record and a name, which is what ended the tool loss and the spending nobody could account for.",
        stack: ["Python", "React", "TypeScript", "Supabase", "PostgreSQL", "Docker"],
        reads: [{ v: "4", l: "cities" }],
      },
      {
        id: "purchasing",
        logo: "/logos/diprolam.png",
        desig: "DPL-PUR/05",
        org: "Diprolam",
        year: "2026",
        statusLabel: "In production",
        status: "pass",
        access: { label: "Internal use", public: false },
        title: "Purchasing, end to end",
        desc: "The whole purchasing process of the four cities in one place: the request, the approval, the purchase order, the supplier and the reception of what arrives, so buying runs as one tracked flow instead of a manual chain that only a few people could follow.",
        stack: ["Python", "React", "TypeScript", "Supabase", "PostgreSQL", "REST APIs"],
        reads: [
          { v: "−36%", l: "process time" },
          { v: "+27%", l: "productivity" },
          { v: "4", l: "cities" },
        ],
      },
      {
        id: "nidal-site",
        logo: "/logos/nidal.png",
        logoShape: "wide",
        desig: "NDL-WEB/06",
        org: "Freelance · Nidal Arquitectura",
        year: "2026",
        statusLabel: "Delivered",
        status: "pass",
        access: { label: "Live site", public: true },
        url: "https://nidalarquitectura.com/",
        title: "Nidal Arquitectura — studio site",
        desc: "Site for the Nidal architecture studio built on TanStack Start and React 19 with file-based routing, where every built work, every piece of news and the studio itself gets its own page rather than being squeezed into a gallery that treats all the projects the same.",
        stack: ["TanStack Start", "TanStack Router", "React 19", "TypeScript", "Tailwind CSS v4", "Vercel"],
        reads: [],
      },
      {
        id: "nidal-admin",
        logo: "/logos/nidal.png",
        logoShape: "wide",
        desig: "NDL-CMS/07",
        org: "Freelance · Nidal Arquitectura",
        year: "2026",
        statusLabel: "Delivered",
        status: "pass",
        access: { label: "Internal use", public: false },
        title: "Nidal — internal admin panel",
        desc: "Admin panel behind a login so the studio publishes on its own, covering projects, news, categories, media, the studio page, contact, users, translations and site settings, which is what keeps new work from having to come through me every time.",
        stack: ["TanStack Start", "React 19", "TypeScript", "shadcn/ui", "Supabase", "Tailwind CSS v4"],
        reads: [{ v: "10", l: "panel sections" }],
      },
      {
        id: "solido-site",
        logo: "/logos/solido.png",
        desig: "SLD-WEB/08",
        org: "Freelance · Sólido Soluciones",
        year: "2026",
        statusLabel: "Delivered",
        status: "pass",
        access: { label: "Public site", public: true },
        title: "Sólido Soluciones — public site",
        desc: "Site for Sólido Soluciones Integrales with its services, its projects and a quote request that ends in a WhatsApp conversation, built with self-hosted fonts and hand-written transitions so it loads fast without leaning on a theme or a third party for its motion.",
        stack: ["React", "Vite", "JavaScript", "Lucide"],
        reads: [],
      },
      {
        id: "solido-system",
        logo: "/logos/solido.png",
        desig: "SLD-SYS/09",
        org: "Freelance · Sólido Soluciones",
        year: "2026",
        statusLabel: "Delivered",
        status: "pass",
        access: { label: "Internal use", public: false },
        title: "Sólido — internal management system",
        desc: "Internal system where each role sees its own work: an administrator and a supervisor see everything, a technician only the work orders assigned to them and an estimator only the quotes they own, with clients, evidence, activity history, notifications and the PDF that comes out at the end of a job.",
        stack: ["React", "Vite", "JavaScript", "Lucide"],
        reads: [{ v: "4", l: "roles" }],
      },
      {
        id: "ai",
        logo: "/logos/megamedia.png",
        desig: "MEG-AI/10",
        org: "Grupo Megamedia",
        year: "2025–26",
        statusLabel: "In production",
        status: "pass",
        access: { label: "Internal use", public: false },
        title: "AI integrations across a century-old newspaper",
        desc: "Python receipt automation, ChatGPT-API financial summaries, Zoho, WooCommerce and ElevenLabs integrations, and support and lead-generation chatbots adopted company-wide at Diario de Yucatán, all kept in step by real-time data synchronization across platforms.",
        stack: ["Python", "OpenAI API", "Zoho CRM", "WooCommerce", "ElevenLabs", "REST APIs"],
        reads: [{ v: "company-wide", l: "chatbot adoption" }],
      },
      {
        id: "ocr",
        logo: "/logos/diario.png",
        desig: "MEG-OCR/11",
        org: "Grupo Megamedia",
        year: "2024",
        statusLabel: "In production",
        status: "pass",
        access: { label: "Internal use", public: false },
        title: "Hemeroteca — OCR search over a century of print",
        desc: "Full-text search over the digitized archive of a century-old newspaper, built for the Hemeroteca portal the newsroom uses in house, so a single page can be pulled out of decades of scanned print, with OCR turning the scans into text the search can actually reach.",
        stack: ["Nuxt", "Vue.js", "Vuetify", "MongoDB", "OCR", "Anthropic Claude"],
        reads: [],
      },
      {
        id: "empleate",
        logo: "/logos/empleate.png",
        desig: "MEG-BOT/12",
        org: "Grupo Megamedia",
        year: "2024",
        statusLabel: "In production",
        status: "pass",
        access: { label: "Publicly accessible", public: true },
        title: "Empléate.app — hiring chatbot",
        desc: "Conversational chatbot on the public job board Empléate.app that walks candidates through registration and their applications without anyone on the other side, paired with AI automation that spots promoted vacancies and puts them in front of the right applicants, on a site open to anyone even if the numbers behind it are not mine to publish.",
        stack: ["Chatbase", "Anthropic Claude", "Nuxt", "Vue.js", "MongoDB", "REST APIs"],
        reads: [],
      },
      {
        id: "survey",
        desig: "FRL-SRV/13",
        org: "Freelance",
        year: "2022–23",
        statusLabel: "Delivered",
        status: "pass",
        access: { label: "Internal use", public: false },
        title: "Field surveys: capture, live monitoring and statistics",
        desc: "Software built for a campaign in the political sector where field teams captured survey responses and a dashboard showed them as they landed, with every answer kept in a structured base in the spirit of Airtable so the team could filter it, export it and pull the breakdowns and statistics a campaign actually runs on, reading where it stood during the day instead of waiting for a count that arrived the morning after.",
        stack: ["React", "TypeScript", "Python", "MongoDB"],
        reads: [{ v: "1 year", l: "of build" }],
      },
      {
        id: "shops",
        desig: "FRL-WEB/14",
        org: "Freelance",
        year: "2022–23",
        statusLabel: "Delivered",
        status: "pass",
        access: { label: "Publicly accessible", public: true },
        title: "Sites and online stores for local businesses",
        desc: "Websites and online stores built in React for small businesses around Mérida, each one with its own catalogue, its orders and the pages the owner actually needed, instead of a template that forces the business to fit whatever the theme allows.",
        stack: ["React", "TypeScript", "Tailwind CSS"],
        reads: [],
      },
      {
        id: "bots",
        desig: "FRL-BOT/15",
        org: "Freelance",
        year: "2022–23",
        statusLabel: "Delivered",
        status: "pass",
        access: { label: "Internal use", public: false },
        title: "Small automations for clients",
        desc: "Simple bots in Python for clients who were doing the same task by hand every day, the kind of work nobody wants and everybody keeps doing because moving it into software never seems urgent enough.",
        stack: ["Python", "REST APIs"],
        reads: [],
      },
    ],
  },

  sites: {
    title: "Site index — MX",
    note: "base + 4 operating sites",
    rows: [
      { code: "MID", name: "Mérida", lat: "20.9674 N", lon: "89.5926 W", fn: "Base of operations", base: true },
      { code: "MTY", name: "Monterrey", lat: "25.6866 N", lon: "100.3161 W", fn: "Diprolam · ERP, CRM, inventory and purchasing", base: false },
      { code: "GTO", name: "Guanajuato", lat: "21.0190 N", lon: "101.2574 W", fn: "Diprolam · ERP, CRM, inventory and purchasing", base: false },
      { code: "PUE", name: "Puebla", lat: "19.0414 N", lon: "98.2063 W", fn: "Diprolam · ERP, CRM, inventory and purchasing", base: false },
      { code: "TIJ", name: "Tijuana", lat: "32.5149 N", lon: "117.0382 W", fn: "Diprolam · ERP, CRM, inventory and purchasing", base: false },
    ],
  },

  builds: {
    title: "Public builds — live demos",
    note: (count) => `${count} units deployed`,
    demo: "Live demo",
    text: {
      4: {
        category: "Internal system",
        summary: "Inventory and requisitions",
        description:
          "Inventory and requisition system for a company with several sites: stock is the sum of every entry, exit and adjustment rather than a number that gets overwritten, so the history stays auditable. Requisitions move through states and are charged to the project they belong to, and permissions are enforced in the database, not by hiding buttons.",
      },
      1: {
        category: "E-commerce",
        summary: "E-commerce storefront",
        description:
          "Full online store with shopping cart, checkout, product comparison, reviews, wishlist and an admin dashboard, including user authentication, order management and role-based permissions.",
      },
      2: {
        category: "Analytics",
        summary: "Crypto analytics dashboard",
        description: "Cryptocurrency dashboard with real-time data visualization and customizable reports.",
      },
      3: {
        category: "Productivity",
        summary: "Task management app",
        description: "Task management app with collaboration features and notifications.",
      },
      6: {
        category: "Visualization",
        summary: "Heart rate simulator",
        description: "Interactive heart rate visualizer with real-time animations and configurable metrics.",
      },
      7: {
        category: "Booking",
        summary: "Booking system",
        description:
          "Booking and ordering web app for the El Taquito Gordo Feliz taquería, where customers book appointments or place orders, receive automated notifications and set reminders.",
      },
    },
  },

  resume: {
    title: "Resume",
    note: "4.5+ years · 7 roles",
    summary:
      "I am an AI Software Engineer and Full Stack Developer with 4.5+ years behind me building business software, AI integrations and process automation, and today I lead IT and software engineering at Diprolam, where the CRM, the inventory system and the purchasing flow run in production while the corporate ERP for more than 100 people and a multi-tenant SaaS platform are still in my hands, after two years at Grupo Megamedia and its newspaper Diario de Yucatán on LLM integrations, chatbots and OCR search over the archive, and a year on my own building sites and small automations for local businesses.",
    experienceLabel: "Experience",
    educationLabel: "Education",
    courseworkLabel: "Relevant coursework",
    roles: [
      {
        id: "diprolam",
        role: "Head of IT & Software Engineering",
        company: "Diprolam",
        location: "MTY · GTO · PUE · TIJ, Mexico",
        dates: "Feb 2026 — Present",
        bullets: [
          "Lead technology operations across the company's four cities, keeping critical systems, infrastructure and business services available",
          "Built and shipped the enterprise CRM now in production, where customers, the pipeline and every open opportunity live",
          "Built the inventory system running in the four cities, where every movement carries a record and a name, which ended the tool loss and the spending nobody could account for",
          "Built the purchasing system that covers the request, the approval, the purchase order, the supplier and the reception, saving 36% of process time and raising productivity 27%",
          "Architect the corporate ERP, in development, for more than 100 people, centralizing inventory, procurement, warehouse, supplier and administrative processes",
          "Design a multi-tenant SaaS platform, in development, with authentication, file storage, document generation and role-based access control",
          "Manage cloud infrastructure on Linux, Docker, AWS and DigitalOcean, and define cybersecurity policies, backups and disaster recovery plans",
        ],
        tech: [
          "Python",
          "React 19",
          "TypeScript",
          "TanStack",
          "Tailwind CSS v4",
          "Supabase",
          "PostgreSQL",
          "Docker",
          "AWS",
          "DigitalOcean",
          "Linux",
        ],
      },
      {
        id: "megamedia",
        role: "AI Solutions Engineer & Project Lead",
        company: "Grupo Megamedia",
        location: "Mérida, Mexico",
        dates: "Aug 2025 — Jan 2026",
        concurrent: "Group-level role, held alongside the Diario de Yucatán position below",
        bullets: [
          "Coordinated and implemented AI and automation projects across several business areas of the group",
          "Designed and integrated conversational AI systems, backend services and workflow automations",
          "Built API integrations and backend services with Python, FastAPI and PostgreSQL",
          "Evaluated emerging AI tools and automation platforms and recommended which ones to adopt",
        ],
        tech: ["Python", "FastAPI", "OpenAI API", "LLMs", "n8n", "Docker", "PostgreSQL", "React"],
      },
      {
        id: "dy-ai",
        role: "AI & API Software Developer",
        company: "Diario de Yucatán (Grupo Megamedia)",
        location: "Mérida, Mexico",
        dates: "Jan 2025 — Feb 2026",
        concurrent: "Ran in parallel with the group-level role above",
        bullets: [
          "Built an automated accounting receipt system in Python that replaced a manual process",
          "Integrated the ChatGPT API to generate automated financial summaries for management",
          "Integrated WooCommerce, Zoho CRM and ElevenLabs to automate sales and marketing workflows",
          "Designed chatbots for lead generation and customer support, adopted company-wide",
          "Automated real-time data synchronization across platforms",
        ],
        tech: [
          "Python",
          "OpenAI API",
          "REST APIs",
          "WooCommerce API",
          "Zoho CRM",
          "Zoho SalesIQ",
          "ElevenLabs",
          "JavaScript",
        ],
      },
      {
        id: "dy-web",
        role: "Web Developer",
        company: "Diario de Yucatán (Grupo Megamedia)",
        location: "Mérida, Mexico",
        dates: "Jan 2024 — Dec 2024",
        bullets: [
          "Developed the chatbot on the public job board Empléate.app that automated user registration and job applications",
          "Implemented AI-based automation that spots promoted vacancies and puts them in front of the right applicants",
          "Led development of the Hemeroteca portal the newsroom uses in house, with OCR search over a century of digitized print",
          "Optimized performance and stability of web platforms, reducing errors and load times",
        ],
        tech: ["Nuxt", "Vue.js", "Vuetify", "MongoDB", "OCR", "Anthropic Claude", "Chatbase", "WordPress"],
      },
      {
        id: "anahuac-intern",
        role: "Software Engineering Intern",
        company: "Universidad Anáhuac Mayab",
        location: "Mérida, Mexico",
        dates: "Sep 2023 — Jan 2024",
        bullets: [
          "Developed institutional web applications with React, TypeScript and Nuxt",
          "Contributed to the Consultation Center portal and other academic websites",
          "Carried out performance improvements and ongoing maintenance of web platforms",
        ],
        tech: ["React", "TypeScript", "Nuxt", "JavaScript"],
      },
      {
        id: "anahuac-support",
        role: "Technical Support / Bot Developer",
        company: "Universidad Anáhuac Mayab",
        location: "Mérida, Mexico",
        dates: "Feb 2023 — Sep 2023",
        bullets: [
          "Resolved user issues through a ticketing system and direct support",
          "Developed a Discord bot with Python and the OpenAI API for automation and community management",
        ],
        tech: ["Python", "OpenAI API", "REST APIs", "Git"],
      },
      {
        id: "freelance",
        role: "Freelance Web Developer",
        company: "Self-employed",
        location: "Mérida, Mexico",
        dates: "Mar 2022 — Jan 2023",
        bullets: [],
        tech: [],
        projects: [
          {
            name: "Survey software for a political campaign",
            meta: "Most of the year · React · TypeScript · Python · MongoDB",
            bullets: [
              "Built the field capture the teams on the street used to record every survey as they walked it",
              "Built the dashboard that showed the answers as they landed, so the campaign could read the day while it was still happening",
              "Kept every answer in a structured base, in the spirit of Airtable, so the data could be filtered, crossed and exported",
              "Produced the breakdowns and statistics the campaign made its decisions on",
            ],
            tech: ["React", "TypeScript", "Python", "MongoDB"],
          },
          {
            name: "Sites and online stores for local businesses",
            bullets: [
              "Built each site and store in React instead of a template, with the catalogue, the orders and the pages the owner actually needed",
            ],
            tech: ["React", "TypeScript", "Tailwind CSS"],
          },
          {
            name: "Small automations for clients",
            bullets: [
              "Wrote simple bots in Python for clients who were repeating the same task by hand every single day",
            ],
            tech: ["Python", "REST APIs"],
          },
        ],
      },
    ],
    education: {
      degree: "Bachelor's Degree in Information Technology and Digital Business",
      school: "Universidad Anáhuac Mayab",
      location: "Mérida, Mexico",
      dates: "Aug 2020 — Dec 2024",
      coursework: [
        "Web Application Development",
        "Software Testing & QA",
        "Advanced Database Design & Optimization",
        "Data Analysis & Intelligent Data Processing",
      ],
    },
  },

  skills: {
    title: "Skills, certifications & courses",
    note: "8 groups · 5 certs · 12 courses",
    certificationsLabel: "Certifications",
    coursesLabel: "Courses",
    groups: [
      { cat: "Languages", items: ["Python", "TypeScript", "JavaScript", "SQL"] },
      {
        cat: "Frontend",
        items: [
          "React 19",
          "Next.js",
          "TanStack Start/Router/Query",
          "Vue.js",
          "Nuxt",
          "Vuetify",
          "React Native",
          "Tailwind CSS v4",
          "shadcn/ui",
          "Vite",
        ],
      },
      {
        cat: "Backend & apis",
        items: ["FastAPI", "Flask", "Django", "Express", "REST APIs", "GraphQL", "Microservices", "Zod"],
      },
      {
        cat: "Ai & automation",
        items: [
          "OpenAI API",
          "Anthropic Claude",
          "LangChain",
          "LLM integrations",
          "AI agents",
          "Conversational AI",
          "OCR",
          "Chatbase",
          "Botpress",
          "ElevenLabs",
          "n8n",
        ],
      },
      { cat: "Databases", items: ["PostgreSQL", "Supabase", "MongoDB", "MySQL", "Redis"] },
      {
        cat: "Cloud & infra",
        items: ["AWS", "DigitalOcean", "Vercel", "Docker", "Kubernetes", "Linux", "CI/CD", "Backups & DRP"],
      },
      {
        cat: "Business platforms",
        items: [
          "ERP / CRM / SaaS development",
          "Zoho CRM",
          "Zoho SalesIQ",
          "Zoho Marketing Automation",
          "Zoho Inventory",
          "Zoho Books",
          "WooCommerce",
          "WordPress",
        ],
      },
      { cat: "Tools", items: ["Git", "GitHub", "FlutterFlow"] },
    ],
    certifications: [
      { no: "01", name: "AWS Certified Cloud Practitioner (CLF-C02)", issuer: "Amazon Web Services", year: "2026" },
      { no: "02", name: "CCNA", issuer: "Cisco", year: "2026" },
      { no: "03", name: "Associate Cloud Engineer", issuer: "Google Cloud", year: "2026" },
      { no: "04", name: "AI Engineer for Developers Associate", issuer: "", year: "2026" },
      { no: "05", name: "SOC", issuer: "Cisco", year: "2026" },
    ],
    courses: [
      "Generative AI with LLMs — DeepLearning.AI",
      "Machine Learning with Python — Coursera",
      "Designing ML Workflows in Python",
      "Software Development with Claude Code",
      "Advanced AI-Assisted Coding",
      "Advanced Prompt Engineering",
      "AWS Cloud Development",
      "Docker & Kubernetes: The Practical Guide",
      "Full-Stack Web Development with React",
      "Data Structures and Algorithms",
      "Google Business Intelligence",
      "SAP Professional Fundamentals",
    ],
  },

  contact: {
    title: "Contact",
    note: "Open to AI and full-stack roles",
    headline: "Available for work on",
    headlineAccent: "AI systems",
    headlineTail: "and full-stack platforms.",
    body: "I am based in Mérida, Yucatán, I work remotely without trouble and I am open to relocating, so write to me and you will usually have an answer the same day.",
    channels: [
      { label: "Email", value: "mednov@outlook.es", href: "mailto:mednov@outlook.es", copy: "mednov@outlook.es" },
      { label: "Phone", value: "+52 999 359 0366", href: "tel:+529993590366", copy: "+52 999 359 0366" },
      { label: "GitHub", value: "github.com/DimitriMedNov", href: "https://github.com/DimitriMedNov" },
      {
        label: "LinkedIn",
        value: "linkedin.com/in/dimitrimednoov",
        href: "https://www.linkedin.com/in/dimitrimednoov",
      },
    ],
  },

  notFound: {
    title: "Route not found",
    note: "no such endpoint",
    body: "That route is not part of this console, so head back to the identity view and pick a tab above.",
    cta: "Return to identity",
  },
};
