import type { Content } from "@/content/types";

/**
 * Contenido en español. Toda cifra aquí es real o no aparece — nunca se estima
 * una métrica para llenar un hueco.
 */
export const es: Content = {
  lang: "es",

  sheets: [
    {
      path: "/",
      tab: "Identidad",
      seoTitle: "Dimitri MedNov",
      seoDescription:
        "Identidad y resultados medidos de Jesus D'mitri Medina Novelo: CRM y automatizaciones en producción en Diprolam, y un ERP para más de 100 usuarios en desarrollo.",
    },
    {
      path: "/systems",
      tab: "Sistemas",
      seoTitle: "Sistemas",
      seoDescription:
        "Trabajo empresarial privado: ERP corporativo, SaaS multi-tenant, CRM empresarial, integraciones de IA y búsqueda con OCR, con las sedes donde operan.",
    },
    {
      path: "/projects",
      tab: "Proyectos",
      seoTitle: "Proyectos públicos",
      seoDescription:
        "Proyectos públicos con su código: InventaPro, ShopEdge, Chainlytics, MindTask, Beat Pulse y El Taquito Gordo Feliz.",
    },
    {
      path: "/about",
      tab: "CV",
      seoTitle: "CV",
      seoDescription:
        "CV completo: 4.5+ años en Diprolam, Grupo Megamedia y Universidad Anáhuac Mayab, con responsabilidades, stack, formación, certificaciones y cursos.",
    },
    {
      path: "/contact",
      tab: "Contacto",
      seoTitle: "Contacto",
      seoDescription:
        "Contacta a Jesus D'mitri Medina Novelo — mednov@outlook.es, +52 999 359 0366.",
    },
  ],

  ui: {
    role: "Ingeniería de sistemas con IA",
    availability: "Disponible para trabajar",
    themeToDark: "Cambiar a modo oscuro",
    themeToLight: "Cambiar a modo claro",
    langSwitch: "View in English",
    navLabel: "Secciones",
    skipDemo: "Demo en vivo",
    source: "Código",
    copy: "Copiar",
    copied: "copiado",
    copyFailed: "No se pudo copiar",
    copyFailedHint: "Selecciona el texto y cópialo a mano.",
    modelView: "Vista del modelo",
    inference: "inferencia",
    live: "en vivo",
    units: "4 capas · 21 nodos",
    channelOpen: "canal abierto",
  },

  hero: {
    eyebrow: "Disponible para trabajar",
    name: "Jesus D'mitri",
    surname: "Medina Novelo",
    summary:
      "Dirijo TI e ingeniería de software en Diprolam, un proveedor industrial con sedes en Monterrey, Guanajuato, Puebla y Tijuana, donde el CRM, el inventario y el proceso de compras que construí ya son parte del día a día mientras levanto el ERP en el que van a trabajar más de 100 personas y, junto a él, una plataforma SaaS multi-tenant, después de dos años en Grupo Megamedia y su periódico centenario metiendo IA donde de verdad ahorraba trabajo: chatbots, resúmenes financieros automáticos y búsqueda con OCR en el archivo.",
    ctaSystems: "Ver sistemas",
    ctaContact: "Abrir canal",
  },

  idFields: [
    { k: "Nombre", v: "Dimitri MedNov" },
    { k: "Coordenadas", v: "20.9674 N · 89.5926 W" },
    { k: "Experiencia", v: "4.5+ años" },
    { k: "GitHub", v: "github/DimitriMedNov", href: "https://github.com/DimitriMedNov" },
    { k: "LinkedIn", v: "linkedin/dimitrimednoov", href: "https://www.linkedin.com/in/dimitrimednoov" },
    { k: "Correo", v: "mednov@outlook.es", href: "mailto:mednov@outlook.es" },
    { k: "Teléfono", v: "+52 999 359 0366", href: "tel:+529993590366" },
  ],

  systems: {
    title: "Sistemas — trabajo privado",
    note: "en su mayoría sistemas internos · sin repositorios públicos",
    stackLabel: "Manifiesto de stack",
    resultLabel: "Resultado registrado",
    cases: [
      {
        id: "erp",
        logo: "/logos/diprolam.png",
        desig: "DPL-ERP/01",
        org: "Diprolam",
        year: "2026",
        statusLabel: "En desarrollo",
        status: "test",
        access: { label: "Uso interno", public: false },
        title: "ERP corporativo",
        desc: "Un ERP para más de 100 usuarios en las cuatro ciudades, que junta inventario, compras, almacén, proveedores y la parte administrativa en un solo sistema, en lugar del puñado de herramientas y hojas de cálculo que cada ciudad había ido armando por su lado.",
        stack: ["Python", "React 19", "TypeScript", "TanStack", "Supabase", "Docker", "AWS"],
        reads: [
          { v: "+100", l: "usuarios" },
          { v: "4", l: "ciudades" },
        ],
      },
      {
        id: "saas",
        logo: "/logos/diprolam.png",
        desig: "DPL-SAAS/02",
        org: "Diprolam",
        year: "2026",
        statusLabel: "En desarrollo",
        status: "test",
        access: { label: "Uso interno", public: false },
        title: "Plataforma SaaS multi-tenant",
        desc: "Plataforma que lleva el papeleo del negocio a software, con autenticación, almacenamiento de archivos, generación de documentos y control de acceso por roles, hecha multi-tenant para que cada parte de la empresa trabaje en su propio espacio sin pisar a las demás.",
        stack: ["React 19", "TypeScript", "TanStack", "Supabase", "Zod", "Vercel"],
        reads: [],
      },
      {
        id: "crm",
        logo: "/logos/diprolam.png",
        desig: "DPL-CRM/03",
        org: "Diprolam",
        year: "2026",
        statusLabel: "En producción",
        status: "pass",
        access: { label: "Uso interno", public: false },
        title: "CRM empresarial",
        desc: "El CRM donde vive la parte comercial de la empresa en sus cuatro ciudades: los clientes, el embudo, cada oportunidad abierta y el seguimiento que necesita, para que el equipo de ventas deje de cargar todo eso en su cabeza y en sus propios archivos.",
        stack: ["Python", "React", "TypeScript", "Supabase", "PostgreSQL", "Linux", "DigitalOcean"],
        reads: [{ v: "4", l: "ciudades" }],
      },
      {
        id: "inventory",
        logo: "/logos/diprolam.png",
        desig: "DPL-INV/04",
        org: "Diprolam",
        year: "2026",
        statusLabel: "En producción",
        status: "pass",
        access: { label: "Uso interno", public: false },
        title: "Manejo de inventario",
        desc: "Software que sigue cada herramienta y cada artículo en las cuatro sedes, de modo que todo movimiento queda registrado y con un nombre detrás, que es lo que acabó con la pérdida de herramientas y con el gasto que nadie podía explicar.",
        stack: ["Python", "React", "TypeScript", "Supabase", "PostgreSQL", "Docker"],
        reads: [{ v: "4", l: "ciudades" }],
      },
      {
        id: "purchasing",
        logo: "/logos/diprolam.png",
        desig: "DPL-PUR/05",
        org: "Diprolam",
        year: "2026",
        statusLabel: "En producción",
        status: "pass",
        access: { label: "Uso interno", public: false },
        title: "Compras, de principio a fin",
        desc: "Todo el proceso de compras de las cuatro ciudades en un solo lugar: la solicitud, la revisión de existencias, las cotizaciones, el cuadro comparativo, la autorización, la orden de compra y la recepción de lo que llega, de modo que la información se captura una vez y se reutiliza en cada etapa en lugar de recapturarse en cada formato. Antes la solicitud, el cuadro comparativo y la orden se hacían en papel con firmas presenciales y el ciclo podía estirarse hasta unos seis días; hoy ese mismo tramo se cierra el mismo día, normalmente en una o dos horas. Lleva más de ocho mil solicitudes y órdenes, 9,456 cuadros comparativos y más de treinta y cinco mil entradas de almacén desde que entró en operación en junio de 2026.",
        caseHref: "/casos/compras",
        caseLabel: "Leer el caso completo",
        stack: ["Python", "React", "TypeScript", "Supabase", "PostgreSQL", "REST APIs"],
        reads: [
          { v: "+8,000", l: "órdenes de compra" },
          { v: "+35,000", l: "entradas de almacén" },
          { v: "+100", l: "usuarios" },
        ],
      },
      {
        id: "nidal-site",
        logo: "/logos/nidal.png",
        logoShape: "wide",
        desig: "NDL-WEB/06",
        org: "Freelance · Nidal Arquitectura",
        year: "2026",
        statusLabel: "Entregado",
        status: "pass",
        access: { label: "Sitio en vivo", public: true },
        url: "https://nidalarquitectura.com/",
        title: "Nidal Arquitectura — sitio del estudio",
        desc: "Sitio del estudio de arquitectura Nidal, hecho con TanStack Start y React 19 sobre rutas por archivos, donde cada obra construida, cada noticia y el estudio mismo tienen su propia página en vez de quedar apretados en una galería que trata igual a todos los proyectos.",
        stack: ["TanStack Start", "TanStack Router", "React 19", "TypeScript", "Tailwind CSS v4", "Vercel"],
        reads: [],
      },
      {
        id: "nidal-admin",
        logo: "/logos/nidal.png",
        logoShape: "wide",
        desig: "NDL-CMS/07",
        org: "Freelance · Nidal Arquitectura",
        year: "2026",
        statusLabel: "Entregado",
        status: "pass",
        access: { label: "Uso interno", public: false },
        title: "Nidal — panel administrativo interno",
        desc: "Panel detrás de login para que el estudio publique por su cuenta, con proyectos, noticias, categorías, medios, la página del estudio, contacto, usuarios, traducciones y los ajustes del sitio, que es lo que evita que cada obra nueva tenga que pasar por mí.",
        stack: ["TanStack Start", "React 19", "TypeScript", "shadcn/ui", "Supabase", "Tailwind CSS v4"],
        reads: [{ v: "10", l: "secciones del panel" }],
      },
      {
        id: "solido-site",
        logo: "/logos/solido.png",
        desig: "SLD-WEB/08",
        org: "Freelance · Sólido Soluciones",
        year: "2026",
        statusLabel: "Entregado",
        status: "pass",
        access: { label: "Sitio público", public: true },
        title: "Sólido Soluciones — sitio público",
        desc: "Sitio de Sólido Soluciones Integrales con sus servicios, sus proyectos y un flujo de cotización que termina en una conversación de WhatsApp, hecho con fuentes autoalojadas y transiciones escritas a mano para que cargue rápido sin depender de una plantilla ni de un tercero para moverse.",
        stack: ["React", "Vite", "JavaScript", "Lucide"],
        reads: [],
      },
      {
        id: "solido-system",
        logo: "/logos/solido.png",
        desig: "SLD-SYS/09",
        org: "Freelance · Sólido Soluciones",
        year: "2026",
        statusLabel: "Entregado",
        status: "pass",
        access: { label: "Uso interno", public: false },
        title: "Sólido — sistema interno de gestión",
        desc: "Sistema interno donde cada rol ve lo suyo: administrador y supervisor ven todo, el técnico solo las órdenes de trabajo que tiene asignadas y el cotizador solo sus cotizaciones, con clientes, evidencias, historial de actividad, notificaciones y el PDF que sale al cerrar un trabajo.",
        stack: ["React", "Vite", "JavaScript", "Lucide"],
        reads: [{ v: "4", l: "roles" }],
      },
      {
        id: "ai",
        logo: "/logos/megamedia.png",
        desig: "MEG-AI/10",
        org: "Grupo Megamedia",
        year: "2025–26",
        statusLabel: "En producción",
        status: "pass",
        access: { label: "Uso interno", public: false },
        title: "Integraciones de IA en un periódico centenario",
        desc: "Automatización de recibos contables en Python, resúmenes financieros con la API de ChatGPT, integraciones con Zoho, WooCommerce y ElevenLabs, y chatbots de soporte y captación adoptados en todo el Diario de Yucatán, todo sincronizado en tiempo real entre plataformas.",
        stack: ["Python", "OpenAI API", "Zoho CRM", "WooCommerce", "ElevenLabs", "REST APIs"],
        reads: [{ v: "toda la empresa", l: "adopción del chatbot" }],
      },
      {
        id: "ocr",
        logo: "/logos/diario.png",
        desig: "MEG-OCR/11",
        org: "Grupo Megamedia",
        year: "2024",
        statusLabel: "En producción",
        status: "pass",
        access: { label: "Uso interno", public: false },
        title: "Hemeroteca — búsqueda con OCR sobre un siglo de papel",
        desc: "Búsqueda de texto completo sobre el archivo digitalizado de un periódico centenario, hecha para el portal Hemeroteca que la redacción usa de forma interna, de modo que se pueda sacar una página concreta de décadas de impresos escaneados, con OCR convirtiendo los escaneos en texto al que la búsqueda sí llega.",
        stack: ["Nuxt", "Vue.js", "Vuetify", "MongoDB", "OCR", "Anthropic Claude"],
        reads: [],
      },
      {
        id: "empleate",
        logo: "/logos/empleate.png",
        desig: "MEG-BOT/12",
        org: "Grupo Megamedia",
        year: "2024",
        statusLabel: "En producción",
        status: "pass",
        access: { label: "Accesible al público", public: true },
        title: "Empléate.app — chatbot de contratación",
        desc: "Chatbot conversacional en la bolsa de trabajo pública Empléate.app que lleva a los candidatos por el registro y sus postulaciones sin nadie del otro lado, junto con automatización con IA que detecta las vacantes promocionadas y las pone frente a los postulantes adecuados, en un sitio abierto a cualquiera aunque las cifras detrás no me toque publicarlas.",
        stack: ["Chatbase", "Anthropic Claude", "Nuxt", "Vue.js", "MongoDB", "REST APIs"],
        reads: [],
      },
      {
        id: "survey",
        desig: "FRL-SRV/13",
        org: "Freelance",
        year: "2022–23",
        statusLabel: "Entregado",
        status: "pass",
        access: { label: "Uso interno", public: false },
        title: "Encuestas en campo: captura, monitoreo en vivo y estadísticas",
        desc: "Software hecho para una campaña del sector político, donde los equipos en calle capturaban las respuestas y un tablero las mostraba conforme iban entrando, con cada respuesta guardada en una base estructurada al estilo de Airtable para filtrarla, exportarla y sacar los cruces y las estadísticas con los que una campaña realmente trabaja, leyendo cómo iba el día en lugar de esperar el conteo de la mañana siguiente.",
        stack: ["React", "TypeScript", "Python", "MongoDB"],
        reads: [{ v: "1 año", l: "de desarrollo" }],
      },
      {
        id: "analytics-mx",
        desig: "FRL-PLT/14",
        org: "Freelance",
        year: "2024",
        statusLabel: "Entregado",
        status: "pass",
        access: { label: "Código público", public: true },
        repos: [
          { label: "API en Go", href: "https://github.com/DimitriMedNov/Analytics" },
          { label: "Panel web en Nuxt", href: "https://github.com/DimitriMedNov/analytics-nuxt" },
          { label: "App móvil en Flutter", href: "https://github.com/DimitriMedNov/Analytics-flutter" },
        ],
        title: "Analytics MX — plataforma de encuestas",
        desc: "A diferencia del trabajo de la campaña, que resolvía una operación concreta, aquí el encargo era una plataforma que sirviera para cualquier encuesta, así que lo importante es que una encuesta no se programa sino que se define: las preguntas viven en un catálogo aparte y se reutilizan entre formularios, cada formulario decide cuáles son obligatorias y cuáles aparecen sólo si otra se respondió de cierta forma, y tanto el panel web como la app móvil dibujan el formulario a partir de esa definición, de manera que dar de alta una encuesta nueva es meterla a la base y no escribir código. Las respuestas se guardan con la ubicación desde donde se levantaron, que es lo que permite leer un resultado por zona y no sólo en total. Son tres piezas sobre la misma API: el backend, el panel donde se arman y se revisan las encuestas, y la app con la que se captura en la calle. En el backend las consultas se generan con sqlc a partir del SQL, así que un cambio de esquema rompe la compilación en vez de fallar en producción, y las migraciones van embebidas en el binario y se aplican al arrancar.",
        stack: ["Go", "chi", "pgx", "PostgreSQL", "sqlc", "Nuxt 3", "Drizzle ORM", "Flutter", "Dart"],
        reads: [{ v: "3", l: "piezas sobre una API" }],
      },
      {
        id: "shops",
        desig: "FRL-WEB/15",
        org: "Freelance",
        year: "2022–23",
        statusLabel: "Entregado",
        status: "pass",
        access: { label: "Accesible al público", public: true },
        title: "Sitios y tiendas en línea para negocios locales",
        desc: "Sitios y tiendas en línea hechos en React para negocios pequeños, cada uno con su catálogo, sus pedidos y las páginas que el dueño de verdad necesitaba, en vez de una plantilla que obliga al negocio a acomodarse a lo que el tema permite.",
        stack: ["React", "TypeScript", "Tailwind CSS"],
        reads: [],
      },
      {
        id: "bots",
        desig: "FRL-BOT/16",
        org: "Freelance",
        year: "2022–23",
        statusLabel: "Entregado",
        status: "pass",
        access: { label: "Uso interno", public: false },
        title: "Automatizaciones pequeñas para clientes",
        desc: "Bots sencillos en Python para clientes que hacían la misma tarea a mano todos los días, de ese trabajo que nadie quiere y que todos siguen haciendo porque pasarlo a software nunca parece lo bastante urgente.",
        stack: ["Python", "REST APIs"],
        reads: [],
      },
    ],
  },

  caseStudy: {
    seoTitle: "Caso: compras de principio a fin",
    seoDescription:
      "Cómo un proceso de compras en papel, con firmas presenciales y un ciclo de hasta seis días, pasó a cerrarse el mismo día: el problema, las decisiones y cómo se mide el resultado.",
    back: "Volver a sistemas",
    eyebrow: "Caso de estudio · Proveedor industrial con cuatro plantas",
    title: "Compras, de principio a fin",
    lede:
      "Comprar un tornillo podía tardar seis días, y ninguno de esos días era por el proveedor. Este es el recorrido de un proceso que vivía en papel, con firmas presenciales y la misma información recapturada en cada formato, hasta un flujo donde se captura una vez y se reutiliza en cada etapa.",
    figures: [
      { v: "+8,000", l: "órdenes de compra" },
      { v: "9,456", l: "cuadros comparativos" },
      { v: "+35,000", l: "entradas de almacén" },
      { v: "+100", l: "usuarios" },
    ],
    sections: [
      {
        id: "problema",
        title: "El problema no era el papel",
        body: [
          "Es fácil contar esto como una historia de digitalización, y sería quedarse corto. El papel era el síntoma: lo que costaba tiempo era que el proceso estaba repartido entre formatos, personas y áreas que no se hablaban entre sí.",
          "Una necesidad de material se convertía en una solicitud física que había que imprimir y pasear para juntar firmas, luego alguien revisaba existencias, pedía al menos tres cotizaciones, armaba a mano un cuadro comparativo con condiciones, tiempos de entrega, descuentos, subtotales e impuestos, y de ahí salía la orden de compra que volvía a subir a firma. Cada salto era una recaptura de los mismos datos y una oportunidad nueva de equivocarse al transcribir.",
          "Saber en qué iba una compra significaba mandar un correo o ir a preguntarle al responsable. No existía un lugar donde mirarlo.",
        ],
      },
      {
        id: "decisiones",
        title: "La decisión que ordena todo lo demás",
        body: [
          "La pieza central no fue una pantalla sino una regla: la información se captura una vez y se reutiliza. El proveedor, las cantidades, las descripciones, el proyecto al que se carga y quién lo pidió se escriben en la solicitud y de ahí viajan solos al cuadro comparativo y a la orden de compra.",
          "Eso elimina de golpe los puntos donde alguien volvía a teclear lo mismo, que eran justo donde aparecían los errores de transcripción. Los cálculos de subtotales, impuestos y totales dejan de hacerse a mano, y las autorizaciones y rechazos quedan registrados con quién, cuándo y por qué motivo.",
          "Quince etapas del flujo viven dentro del sistema, de la solicitud hasta la recepción final, pasando por entradas a almacén, resguardos y traspasos. No es que el departamento entero esté automatizado, es que ese recorrido completo dejó de salirse a un formato suelto.",
        ],
      },
      {
        id: "medicion",
        title: "Cómo se mide, y qué no se puede medir",
        body: [
          "Antes, la solicitud, el cuadro comparativo y la orden tomaban alrededor de dos días cada uno contando elaboración, revisiones, firmas y esperas, así que el tramo administrativo podía estirarse hasta unos seis días. Hoy ese mismo tramo se cierra el mismo día, normalmente en una o dos horas, para procesos que traen entre diez y quince artículos.",
          "Ese antes es una estimación de quienes operaban el proceso, no un dato medido: el flujo en papel no dejaba marcas de tiempo, así que no hay con qué compararlo automáticamente. Los números de volumen sí salen del sistema, porque los registra él.",
          "El tiempo del proveedor queda fuera a propósito. Si una entrega tarda quince días por fabricación o logística, eso no lo arregla ningún software y no tiene por qué apuntarse a su favor. La medición termina donde termina el trabajo administrativo: en la orden autorizada.",
        ],
      },
      {
        id: "resultado",
        title: "Qué cambió en la práctica",
        body: [
          "Una solicitud ya no se persigue: se consulta. El estado, quién la tiene pendiente, qué se autorizó y qué se rechazó y por qué están en la misma pantalla, así que el seguimiento dejó de ser una cadena de correos.",
          "La operación ordinaria es prácticamente sin papel, aunque alguna orden se imprime por excepción para ciertas auditorías, de modo que decir que el papel desapareció del todo sería falso.",
          "Y hay una cosa que no estaba en el plan y resultó valiosa: como cada movimiento queda con responsable y fecha, el historial sirve para responder preguntas que antes nadie hacía porque no había forma de contestarlas.",
        ],
      },
    ],
    honesty: {
      title: "Lo que este caso no demuestra",
      items: [
        "No hay reducción de costos medida: no existen los datos económicos para sostenerla.",
        "No hay reducción de errores medida: se quitaron los puntos de recaptura, pero nunca se contaron los errores del proceso anterior, así que no hay contra qué comparar.",
        "El tiempo ahorrado es de ciclo, no de horas trabajadas: los seis días anteriores incluían esperas y firmas, no eran seis días de alguien sentado frente al expediente.",
        "Las cifras de volumen son de entidades distintas del mismo proceso y no deben sumarse entre sí: una solicitud, su cuadro comparativo y su orden son el mismo caso contado tres veces.",
      ],
    },
    note:
      "Este caso se publica sin el nombre de la empresa, sin referencias a sus documentos internos y sin datos de su operación, con autorización para contar el trabajo.",
  },

  sites: {
    title: "Sedes de Diprolam que usan estos sistemas",
    note: "4 plantas, un mismo ERP",
    rows: [
      { code: "MTY", name: "Monterrey", lat: "25.6866 N", lon: "100.3161 W", fn: "ERP, CRM, inventario y compras" },
      { code: "GTO", name: "Guanajuato", lat: "21.0190 N", lon: "101.2574 W", fn: "ERP, CRM, inventario y compras" },
      { code: "PUE", name: "Puebla", lat: "19.0414 N", lon: "98.2063 W", fn: "ERP, CRM, inventario y compras" },
      { code: "TIJ", name: "Tijuana", lat: "32.5149 N", lon: "117.0382 W", fn: "ERP, CRM, inventario y compras" },
    ],
  },

  builds: {
    title: "Proyectos públicos",
    note: (count) => `${count} proyectos`,
    demo: "Demo en vivo",
    openChat: "Escríbele por WhatsApp",
    codePrivate: "Código privado",
    text: {
      4: {
        category: "Sistema interno",
        summary: "Inventario y requisiciones",
        description:
          "Sistema de inventario y requisiciones para una empresa con varias sedes, donde el stock se calcula sumando cada entrada, salida y ajuste en vez de sobrescribir un número, de manera que cualquier movimiento se puede rastrear hasta su origen, y donde las requisiciones recorren sus estados cargándose al proyecto que corresponde mientras los permisos se aplican en la base de datos y no escondiendo botones. La demo abre con datos de ejemplo y se entra con el botón de invitado, sin registro.",
      },
      1: {
        category: "E-commerce",
        summary: "Tienda en línea",
        description:
          "Tienda en línea completa donde el cliente arma su carrito, compara productos, deja reseñas y guarda su wishlist hasta llegar al pago, mientras del otro lado un panel de administración lleva el catálogo y las órdenes con permisos por rol.",
      },
      2: {
        category: "Analítica",
        summary: "Dashboard de criptomonedas",
        description:
          "Panel de criptomonedas que sigue los precios en tiempo real y deja armar un portafolio y una lista de seguimiento, con un analista de IA que lee el mercado del momento y lo resume en lenguaje llano.",
      },
      3: {
        category: "IA local",
        summary: "Tareas con IA que funciona sin internet",
        description:
          "Gestor de tareas que corre entero en tu máquina, con su base de datos, su modelo y su dictado, y donde el proveedor de IA es intercambiable, así que lo mismo funciona con Ollama en local que con tu propia llave de OpenAI o Anthropic o con cualquier servidor compatible, y si no configuras ninguno la app sigue trabajando sin sus funciones de IA en lugar de tronar. Dictas una tarea hablando normal y el texto se va escribiendo mientras hablas, con la transcripción viviendo también en tu computadora, mientras el mismo intérprete que lee lo dictado saca la fecha, la prioridad y la categoría de una frase suelta. La capa de IA está medida y acotada: tiempo límite por llamada, reintentos solo ante fallas pasajeras y un registro de cada consulta que el repo convierte en medianas y percentiles.",
      },
      6: {
        category: "Visualización",
        summary: "Simulador de ritmo cardíaco",
        description:
          "Simulador de electrocardiograma para quien está aprendiendo a distinguir ritmos, con siete de ellos y sus firmas reales, desde la fibrilación auricular que se queda sin ondas P hasta el bloqueo donde el intervalo PR se alarga latido a latido hasta que uno no conduce, dibujados sobre papel de electro con su cuadrícula de verdad. El complejo conserva sus tiempos clínicos a cualquier frecuencia, que es justo lo que separa un trazo fiel de una animación que estira la onda entera al acelerar, y el modo examen esconde el ritmo para que lo reconozcas tú, con la explicación apareciendo al responder.",
      },
      8: {
        category: "Bot de WhatsApp",
        summary: "Imágenes convertidas en stickers",
        description:
          "Bot de WhatsApp al que le mandas una imagen y te la regresa convertida en sticker, corriendo como función serverless sobre la Cloud API de Meta. Ninguna imagen se guarda en ningún lado: se descarga, se transforma y se envía, y lo único que queda registrado son el teléfono, los contadores y los datos técnicos del proceso. Los límites por usuario y la idempotencia viven en la base de datos con bloqueo por teléfono en vez de en la memoria del servidor, que es lo que lo mantiene en pie aunque cada mensaje caiga en una instancia distinta, y detrás hay un panel donde se ven el uso, los errores y las alertas. Está funcionando: escríbele al +52 986 102 6628 y mándale una foto.",
      },
      7: {
        category: "Reservas",
        summary: "Sistema de reservas",
        description:
          "App web de reservas y pedidos para la taquería El Taquito Gordo Feliz, donde los clientes agendan o piden desde el celular y reciben sus recordatorios sin que nadie del negocio tenga que estar contestando mensajes.",
      },
    },
  },

  resume: {
    title: "Currículum",
    note: "4.5+ años · 7 puestos",
    summary:
      "Soy ingeniero de software con IA y desarrollador full stack con más de 4.5 años creando software empresarial, integraciones de IA y automatización de procesos, y hoy dirijo TI e ingeniería de software en Diprolam, donde el CRM, el inventario y las compras que construí están en producción mientras el ERP corporativo para más de 100 personas y una plataforma SaaS multi-tenant siguen en mis manos, después de dos años en Grupo Megamedia y su periódico Diario de Yucatán en integraciones con LLM, chatbots y búsqueda con OCR en el archivo, y un año por mi cuenta haciendo sitios y pequeñas automatizaciones para negocios locales.",
    download: "Descargar CV en PDF",
    experienceLabel: "Experiencia",
    educationLabel: "Formación",
    courseworkLabel: "Materias relevantes",
    roles: [
      {
        id: "diprolam",
        role: "Director de TI e Ingeniería de Software",
        company: "Diprolam",
        location: "MTY · GTO · PUE · TIJ, México",
        dates: "Feb 2026 — Actualidad",
        bullets: [
          "Dirijo las operaciones de tecnología en las cuatro ciudades de la empresa, manteniendo disponibles los sistemas críticos, la infraestructura y los servicios del negocio",
          "Construí y lancé el CRM empresarial que hoy está en producción, donde viven los clientes, el embudo y cada oportunidad abierta",
          "Construí el sistema de inventario que corre en las cuatro ciudades, donde cada movimiento queda registrado y con un nombre detrás, lo que acabó con la pérdida de herramientas y con el gasto que nadie podía explicar",
          "Construí el sistema de compras que va de la solicitud a la recepción, donde el ciclo administrativo pasó de estirarse hasta unos seis días a cerrarse el mismo día, y que lleva más de ocho mil órdenes y más de cien usuarios",
          "Diseño el ERP corporativo, en desarrollo, para más de 100 personas, que centraliza inventario, compras, almacén, proveedores y procesos administrativos",
          "Diseño una plataforma SaaS multi-tenant, en desarrollo, con autenticación, almacenamiento de archivos, generación de documentos y control de acceso por roles",
          "Administro la infraestructura en Linux, Docker, AWS y DigitalOcean, y defino las políticas de ciberseguridad, los respaldos y el plan de recuperación ante desastres",
        ],
        tech: [
          "Python",
          "React 19",
          "TypeScript",
          "TanStack",
          "Tailwind CSS v4",
          "Supabase",
          "PostgreSQL",
          "Docker",
          "AWS",
          "DigitalOcean",
          "Linux",
        ],
      },
      {
        id: "megamedia",
        role: "Ingeniero de Soluciones de IA y Líder de Proyecto",
        company: "Grupo Megamedia",
        dates: "Ago 2025 — Ene 2026",
        concurrent: "Puesto a nivel grupo, en paralelo con el del Diario de Yucatán que aparece abajo",
        bullets: [
          "Coordiné e implementé proyectos de IA y automatización en varias áreas del grupo",
          "Diseñé e integré sistemas de IA conversacional, servicios backend y automatizaciones de flujos de trabajo",
          "Construí integraciones de API y servicios backend con Python, FastAPI y PostgreSQL",
          "Evalué herramientas emergentes de IA y plataformas de automatización, y recomendé cuáles adoptar",
        ],
        tech: ["Python", "FastAPI", "OpenAI API", "LLMs", "n8n", "Docker", "PostgreSQL", "React"],
      },
      {
        id: "dy-ai",
        role: "Desarrollador de Software de IA y APIs",
        company: "Diario de Yucatán (Grupo Megamedia)",
        dates: "Ene 2025 — Feb 2026",
        concurrent: "En paralelo con el puesto a nivel grupo de arriba",
        bullets: [
          "Construí un sistema automatizado de recibos contables en Python que reemplazó un proceso manual",
          "Integré la API de ChatGPT para generar resúmenes financieros automáticos para la dirección",
          "Integré WooCommerce, Zoho CRM y ElevenLabs para automatizar flujos de ventas y marketing",
          "Diseñé chatbots de captación y soporte al cliente, adoptados en toda la empresa",
          "Automaticé la sincronización de datos en tiempo real entre plataformas",
        ],
        tech: [
          "Python",
          "OpenAI API",
          "REST APIs",
          "WooCommerce API",
          "Zoho CRM",
          "Zoho SalesIQ",
          "ElevenLabs",
          "JavaScript",
        ],
      },
      {
        id: "dy-web",
        role: "Desarrollador Web",
        company: "Diario de Yucatán (Grupo Megamedia)",
        dates: "Ene 2024 — Dic 2024",
        bullets: [
          "Desarrollé el chatbot de la bolsa de trabajo pública Empléate.app, que automatizó el registro de usuarios y las postulaciones",
          "Implementé automatización con IA que detecta las vacantes promocionadas y las pone frente a los postulantes adecuados",
          "Lideré el desarrollo del portal Hemeroteca que la redacción usa de forma interna, con búsqueda por OCR sobre un siglo de impresos digitalizados",
          "Optimicé el rendimiento y la estabilidad de las plataformas web, reduciendo errores y tiempos de carga",
        ],
        tech: ["Nuxt", "Vue.js", "Vuetify", "MongoDB", "OCR", "Anthropic Claude", "Chatbase", "WordPress"],
      },
      {
        id: "anahuac-intern",
        role: "Practicante de Ingeniería de Software",
        company: "Universidad Anáhuac Mayab",
        dates: "Sep 2023 — Ene 2024",
        bullets: [
          "Desarrollé aplicaciones web institucionales con React, TypeScript y Nuxt",
          "Colaboré en el portal del Centro de Consultoría y en otros sitios académicos",
          "Realicé mejoras de rendimiento y mantenimiento continuo de las plataformas web",
        ],
        tech: ["React", "TypeScript", "Nuxt", "JavaScript"],
      },
      {
        id: "anahuac-support",
        role: "Soporte Técnico / Desarrollador de Bots",
        company: "Universidad Anáhuac Mayab",
        dates: "Feb 2023 — Sep 2023",
        bullets: [
          "Resolví incidencias de usuarios mediante un sistema de tickets y soporte directo",
          "Desarrollé un bot de Discord con Python y la API de OpenAI para automatización y gestión de la comunidad",
        ],
        tech: ["Python", "OpenAI API", "REST APIs", "Git"],
      },
      {
        id: "freelance",
        role: "Desarrollador Web Freelance",
        company: "Por mi cuenta",
        dates: "Mar 2022 — Ene 2023",
        bullets: [],
        tech: [],
        projects: [
          {
            name: "Software de encuestas para una campaña política",
            meta: "La mayor parte del año · React · TypeScript · Python · MongoDB",
            bullets: [
              "Construí la captura en campo que usaban los equipos en calle para levantar cada encuesta mientras la caminaban",
              "Construí el tablero que mostraba las respuestas conforme iban entrando, para que la campaña leyera el día mientras todavía estaba pasando",
              "Guardé cada respuesta en una base estructurada, al estilo de Airtable, para poder filtrar, cruzar y exportar los datos",
              "Saqué los cruces y las estadísticas con las que la campaña tomaba sus decisiones",
            ],
            tech: ["React", "TypeScript", "Python", "MongoDB"],
          },
          {
            name: "Sitios y tiendas en línea para negocios locales",
            bullets: [
              "Hice cada sitio y cada tienda en React en vez de una plantilla, con el catálogo, los pedidos y las páginas que el dueño de verdad necesitaba",
            ],
            tech: ["React", "TypeScript", "Tailwind CSS"],
          },
          {
            name: "Automatizaciones pequeñas para clientes",
            bullets: [
              "Escribí bots sencillos en Python para clientes que repetían la misma tarea a mano todos los días",
            ],
            tech: ["Python", "REST APIs"],
          },
        ],
      },
    ],
    education: {
      degree: "Licenciatura en Tecnologías de Información y Negocios Digitales",
      school: "Universidad Anáhuac Mayab",
      dates: "Ago 2020 — Dic 2024",
      coursework: [
        "Desarrollo de aplicaciones web",
        "Pruebas de software y calidad",
        "Diseño y optimización avanzada de bases de datos",
        "Análisis de datos y procesamiento inteligente",
      ],
    },
  },

  skills: {
    title: "Habilidades, certificaciones y cursos",
    note: "8 grupos · 5 certificaciones · 12 cursos",
    certificationsLabel: "Certificaciones",
    coursesLabel: "Cursos",
    groups: [
      { cat: "Lenguajes", items: ["Python", "TypeScript", "JavaScript", "SQL"] },
      {
        cat: "Frontend",
        items: [
          "React 19",
          "Next.js",
          "TanStack Start/Router/Query",
          "Vue.js",
          "Nuxt",
          "Vuetify",
          "React Native",
          "Tailwind CSS v4",
          "shadcn/ui",
          "Vite",
        ],
      },
      {
        cat: "Backend y apis",
        items: ["FastAPI", "Flask", "Django", "Express", "REST APIs", "GraphQL", "Microservicios", "Zod"],
      },
      {
        cat: "IA y automatización",
        items: [
          "OpenAI API",
          "Anthropic Claude",
          "LangChain",
          "Integraciones con LLM",
          "Agentes de IA",
          "IA conversacional",
          "OCR",
          "Chatbase",
          "Botpress",
          "ElevenLabs",
          "n8n",
        ],
      },
      { cat: "Bases de datos", items: ["PostgreSQL", "Supabase", "MongoDB", "MySQL", "Redis"] },
      {
        cat: "Nube e infraestructura",
        items: ["AWS", "DigitalOcean", "Vercel", "Docker", "Kubernetes", "Linux", "CI/CD", "Respaldos y DRP"],
      },
      {
        cat: "Plataformas de negocio",
        items: [
          "Desarrollo ERP / CRM / SaaS",
          "Zoho CRM",
          "Zoho SalesIQ",
          "Zoho Marketing Automation",
          "Zoho Inventory",
          "Zoho Books",
          "WooCommerce",
          "WordPress",
        ],
      },
      { cat: "Herramientas", items: ["Git", "GitHub", "FlutterFlow"] },
    ],
    certifications: [
      { no: "01", name: "AWS Certified Cloud Practitioner (CLF-C02)", issuer: "Amazon Web Services", year: "2026" },
      { no: "02", name: "CCNA", issuer: "Cisco", year: "2026" },
      { no: "03", name: "Associate Cloud Engineer", issuer: "Google Cloud", year: "2026" },
      { no: "04", name: "AI Engineer for Developers Associate", issuer: "", year: "2026" },
      { no: "05", name: "SOC", issuer: "Cisco", year: "2026" },
    ],
    courses: [
      "IA generativa con LLM — DeepLearning.AI",
      "Machine Learning con Python — Coursera",
      "Diseño de flujos de ML en Python",
      "Desarrollo de software con Claude Code",
      "Programación avanzada asistida por IA",
      "Ingeniería de prompts avanzada",
      "AWS Cloud Development",
      "Docker y Kubernetes: guía práctica",
      "Desarrollo web full-stack con React",
      "Estructuras de datos y algoritmos",
      "Google Business Intelligence",
      "SAP Professional Fundamentals",
    ],
  },

  contact: {
    title: "Contacto",
    note: "Abierto a puestos de IA y full-stack",
    headline: "Disponible para trabajar en",
    headlineAccent: "sistemas de IA",
    headlineTail: "y plataformas full-stack.",
    body: "Trabajo remoto sin problema y estoy abierto a reubicarme, así que escríbeme y normalmente tendrás respuesta el mismo día.",
    channels: [
      { label: "Correo", value: "mednov@outlook.es", href: "mailto:mednov@outlook.es", copy: "mednov@outlook.es" },
      { label: "Teléfono", value: "+52 999 359 0366", href: "tel:+529993590366", copy: "+52 999 359 0366" },
      { label: "GitHub", value: "github.com/DimitriMedNov", href: "https://github.com/DimitriMedNov" },
      {
        label: "LinkedIn",
        value: "linkedin.com/in/dimitrimednoov",
        href: "https://www.linkedin.com/in/dimitrimednoov",
      },
    ],
  },

  notFound: {
    title: "Ruta no encontrada",
    note: "endpoint inexistente",
    body: "Esa ruta no es parte de esta consola, así que vuelve a la vista de identidad y elige una pestaña de arriba.",
    cta: "Volver a identidad",
  },
};
